### ISSUE TITLE
前端项目 dashboard 编译失败

### ISSUE THREAD

**Issue by ufosaga** [mochat-cloud/mochat#103]
## 我用的环境

* PHP 版本：7.4.3
* MoChat 版本：latest
* Swoole 版本：4.6.5
* Nodejs 版本：14.15.3

## 问题及现象
dashboard 编译失败, 看起来是去 require 不存在的 json文件，./public/ 下边没有 dll 文件夹，自然也不会有 dll/antDesignVue-manifest.json, 看起了也不像是 vue 或 webpack 会自动去创建文件夹和下载对应文件。

```
# 报错代码位置：
...
const dll = ['antDesignVue', 'vueCropper', 'echarts', 'corejs', 'vueContainerQuery']
      dll.map(item => {
        const path = `./public/dll/${item}-manifest.json`
        config.plugins.push(new webpack.DllReferencePlugin({
          manifest: require(path)
        }))
      })
...

# 报错命令：
$ yarn run build
yarn run v1.22.10
$ vue-cli-service build
✔  Building for production...
 ERROR  Error: Cannot find module './public/dll/antDesignVue-manifest.json'
Require stack:
- /home/thomas/scp_root/mochat/dashboard/vue.config.js
- /home/thomas/scp_root/mochat/dashboard/package.json
Error: Cannot find module './public/dll/antDesignVue-manifest.json'
Require stack:
- /home/thomas/scp_root/mochat/dashboard/vue.config.js
- /home/thomas/scp_root/mochat/dashboard/package.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/thomas/scp_root/mochat/dashboard/vue.config.js:65:21
    at Array.map (<anonymous>)
    at configureWebpack (/home/thomas/scp_root/mochat/dashboard/vue.config.js:62:11)
    at /home/thomas/scp_root/mochat/dashboard/node_modules/@vue/cli-service/lib/Service.js:251:21
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (/home/thomas/scp_root/mochat/dashboard/node_modules/@vue/cli-service/lib/Service.js:248:30)
    at PluginAPI.resolveWebpackConfig (/home/thomas/scp_root/mochat/dashboard/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at module.exports (/home/thomas/scp_root/mochat/dashboard/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:46:14)
    at build (/home/thomas/scp_root/mochat/dashboard/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at /home/thomas/scp_root/mochat/dashboard/node_modules/@vue/cli-service/lib/commands/build/index.js:89:13
    at Service.run (/home/thomas/scp_root/mochat/dashboard/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/home/thomas/scp_root/mochat/dashboard/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by maxincai** [comment]
先执行 yarn run dll
再执行 yarn run build

**Comment by ufosaga** [comment]
@maxincai 谢谢，好用了。
我提交了更新文档的PR，你可以merge下。
