### ISSUE TITLE
初始化报错php bin/hyperf.php mc:init。  PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\RuntimeException: Unable to hide the response. in /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php:434

### ISSUE THREAD

**Issue by HelkeNarmo** [mochat-cloud/mochat#191]
## 我用的环境

* PHP 版本：7.4
* MoChat 版本：最新（2022.4）
* Swoole 版本：4

## 问题及现象

执行如下指令时报错：`php bin/hyperf.php mc:init`
刚开始初始化时正常，当配置到管理员手机并回车确定时，看到提示输入管理员密码，接着就是报错信息了。
```
 输入redis.db [0]:
 > 

+------------+-----------+
| 属性名称   | 属性值    |
+------------+-----------+
| REDIS_HOST | 127.0.0.1 |
| REDIS_PORT | 6379      |
| REDIS_AUTH |           |
| REDIS_DB   | 0         |
+------------+-----------+
重载配置成功

 输入管理员的手机号:
 > 18888888888

 输入管理员密码:
 > PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\RuntimeException: Unable to hide the response. in /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php:434
```
完整报错信息如下：
```
 > PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\RuntimeException: Unable to hide the response. in /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php:434
Stack trace:
#0 /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php(120): Symfony\Component\Console\Helper\QuestionHelper->getHiddenResponse()
#1 /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php(67): Symfony\Component\Console\Helper\QuestionHelper->doAsk()
#2 /www/wwwroot/mochat/api-server/vendor/symfony/console/Style/SymfonyStyle.php(361): Symfony\Component\Console\Helper\QuestionHelper->ask()
#3 /www/wwwroot/mochat/api-server/vendor/hyperf/command/src/Command.php(182): Symfony\Component\Console\Style\SymfonyStyle->askQuestion()
#4 /www/wwwroot/mochat/api-server/runtime/container/proxy/MoChat_App_Install_Command_McInitCommand.proxy.php(203): Hyperf\Command\Command->secret()
#5 /www/wwwroot/mochat/api-server/runtime/container/proxy/MoChat_App_Install_Command_McInitCommand.pro in /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php on line 434

Fatal error: Uncaught Symfony\Component\Console\Exception\RuntimeException: Unable to hide the response. in /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php:434
Stack trace:
#0 /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php(120): Symfony\Component\Console\Helper\QuestionHelper->getHiddenResponse()
#1 /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php(67): Symfony\Component\Console\Helper\QuestionHelper->doAsk()
#2 /www/wwwroot/mochat/api-server/vendor/symfony/console/Style/SymfonyStyle.php(361): Symfony\Component\Console\Helper\QuestionHelper->ask()
#3 /www/wwwroot/mochat/api-server/vendor/hyperf/command/src/Command.php(182): Symfony\Component\Console\Style\SymfonyStyle->askQuestion()
#4 /www/wwwroot/mochat/api-server/runtime/container/proxy/MoChat_App_Install_Command_McInitCommand.proxy.php(203): Hyperf\Command\Command->secret()
#5 /www/wwwroot/mochat/api-server/runtime/container/proxy/MoChat_App_Install_Command_McInitCommand.pro in /www/wwwroot/mochat/api-server/vendor/symfony/console/Helper/QuestionHelper.php on line 434
```

**Comment by tianwen20** [comment]
我也有同样的错误

**Comment by maxincai** [comment]
取消禁用 exec 和 shell_exec

**Comment by tianwen20** [comment]
我尝试一下，感谢

**Comment by tianwen20** [comment]
成功了

**Comment by HelkeNarmo** [comment]
> 取消禁用 exec 和 shell_exec

成功了，感谢。
